spring:
  application:
    name: spring-ai-jokes

  ai:
    openai:
      api-key: ${AI_API_KEY}

      chat:
        base-url: https://generativelanguage.googleapis.com
        completions-path: /v1beta/openai/chat/completions

        options:
          model: gemini-2.5-flash